apiVersion: apps/v1
kind: Deployment
metadata:
  name: truck-consumer
  labels:
    app: truck-consumer
    app.kubernetes.io/name: truck-consumer
    app.kubernetes.io/component: consumer
    app.kubernetes.io/part-of: project-proximity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: truck-consumer
  template:
    metadata:
      labels:
        app: truck-consumer
    spec:
      containers:
        - name: truck-consumer
          image: truck-consumer:latest
          imagePullPolicy: Always
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "172.30.68.114:9092"
            - name: KAFKA_TOPIC
              value: "truck-telemetry"
            - name: KAFKA_CONSUMER_GROUP
              value: "truck-consumer-group"
            - name: KAFKA_CLIENT_ID
              value: "truck-consumer"
            - name: KAFKA_AUTO_OFFSET_RESET
              value: "earliest"
            - name: KAFKA_SECURITY_PROTOCOL
              value: "PLAINTEXT"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      restartPolicy: Always

